In [1]:
import numpy as np
import cv2
a = np.array([0,0,1,2,3,4,5,6,7,8,9,0,0])
print(np.maximum(a, 1))
print(np.clip(a, 3,5))


[1 1 1 2 3 4 5 6 7 8 9 1 1]
[3 3 3 3 3 4 5 5 5 5 5 3 3]


In [2]:
xx, yy = np.meshgrid(a, a)

In [3]:
print(xx)
print(np.clip(xx, 2,5))

[[0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]]
[[2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]]


In [4]:
from skimage.measure import label

bb = np.array([[0,0,0,0,0,0,0,0,0],
               [0,1,1,1,0,0,0,0,0],
               [0,1,2,1,0,0,0,0,0],
               [0,0,2,0,0,1,1,1,0],
               [0,1,0,0,0,1,1,1,0],
               [0,1,0,0,0,1,1,1,0],
               [0,0,1,0,0,0,0,0,0]])

print(label(bb, connectivity=2, return_num=True))

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 2, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 3, 3, 3, 0],
       [0, 4, 0, 0, 0, 3, 3, 3, 0],
       [0, 4, 0, 0, 0, 3, 3, 3, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0]]), 4)


In [5]:
bbb = np.eye(10, 10)

print(bbb)
print(cv2.dilate(bbb, np.ones((3,3))))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [7]:
aaa = np.zeros((5,5))
bbb = aaa[1:4,1:4]
bbb[:,:] = 1
print(aaa, bbb)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
aaa = np.zeros((5,5))
bbb = aaa[1:4,1:4].copy()
bbb[:,:] = 1
print(aaa, bbb)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
