In [5]:
import numpy as np

a = np.array([0,0,1,2,3,4,5,6,7,8,9,0,0])
print(np.maximum(a, 1))
print(np.clip(a, 3,5))


[1 1 1 2 3 4 5 6 7 8 9 1 1]
[3 3 3 3 3 4 5 5 5 5 5 3 3]


In [6]:
xx, yy = np.meshgrid(a, a)

In [8]:
print(xx)
print(np.clip(xx, 2,5))

[[0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]
 [0 0 1 2 3 4 5 6 7 8 9 0 0]]
[[2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]
 [2 2 2 2 3 4 5 5 5 5 5 2 2]]


In [18]:
from skimage.measure import label

bb = np.array([[0,0,0,0,0,0,0,0,0],
               [0,1,1,1,0,0,0,0,0],
               [0,1,2,1,0,0,0,0,0],
               [0,0,2,0,0,1,1,1,0],
               [0,1,0,0,0,1,1,1,0],
               [0,1,0,0,0,1,1,1,0],
               [0,0,1,0,0,0,0,0,0]])

print(label(bb, connectivity=2, return_num=True))

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 2, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 3, 3, 3, 0],
       [0, 4, 0, 0, 0, 3, 3, 3, 0],
       [0, 4, 0, 0, 0, 3, 3, 3, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0]]), 4)
